site_name: 青年外语社
theme:
    name: material
    language: zh
    logo: images/logo.jpg
    palette:
        primary: white
        accent: blue
nav:
    - 首页: index.md
    - 愿景与纲领: rules.md
    - 加入我们: join.md
    - 资源: resources.md
